### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by qalisto** [markuslohn/tiddlywiki#1]
Hello,
Thank you for great idea.
I just had to migrate back to WIN from LNX.
Any plans to port to a WIN version?
Or ... am I missing an easy workaround besides installing a LNX virtual machine?

Best, -Q

**Comment by markuslohn** [comment]
Because it is only Java-Code you can run this also on Windows.  The only thing is to look in the tw.sh script. This prepares the classpath and finally runs the java -jar command. You can easily adopt this to an batch file running under Windows. Hope that helps.

**Comment by Matthis-wilh** [comment]
Hi,
I´m new to bash and batch files. Could you elaborate how to change the bash file so It will run under windows?
I tried extracting and running just the last java command in the cmd-line (with directories changed), but I still get an error saying the main class couldn´t be found. 

I would be very thankfull for any help

Greetings, 

Matthis

**Comment by markuslohn** [comment]
Ok, you run into a classpath setting problem. I can provide an example, but I don't have a windows environment currently available for testing. Which version of windows you are using?

**Comment by Matthis-wilh** [comment]
I´m running Windows 10 (Enterprise), a sample would already help. 
Thank you

**Comment by markuslohn** [comment]
Hi, attached you find a windows version. However keep in mind that it wasn't tested because I have no windows system available. Hopefully you can get it working.

[scripts.zip](https://github.com/markuslohn/tiddlywiki/files/3988135/scripts.zip)
